version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    container_name: data_transfer_test_app
    command: >
      bash -c "yarn --cwd public/ &&
               whenever -w &&
               /etc/init.d/cron restart &&
               bundle exec ruby app.rb -o 0.0.0.0 -p 4567"
    ports:
      - "4567:4567"
    volumes:
      - .:/code